apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    opentelemetry.io/name: httpd-deployment
    app.kubermetes.io/name: httpd-deployment
    app.kubernetes.io/instance: splunk-datagens
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubermetes.io/name: httpd-deployment
  template:
    metadata:
      labels:
        opentelemetry.io/name: httpd-deployment
        app.kubermetes.io/name: httpd-deployment
        app.kubernetes.io/instance: splunk-datagens
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: stresstest
                operator: NotIn
                values:
                - "true"
      containers:
        - name: apache-httpd
          image: httpd:no_version
          imagePullPolicy: IfNotPresent
  strategy:
    type: Recreate

