apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    opentelemetry.io/name: nginx-deployment
    app.kubermetes.io/name: nginx-deployment
    app.kubernetes.io/instance: splunk-datagens
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubermetes.io/name: nginx-deployment
  template:
    metadata:
      labels:
        opentelemetry.io/name: nginx-deployment
        app.kubermetes.io/name: nginx-deployment
        app.kubernetes.io/instance: splunk-datagens
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: stresstest
                operator: NotIn
                values:
                - "true"
      containers:
      - name: nginx
        image: nginx
        command:
          - "bash"
          - "-c"
          - "count=0 ; sleep 300 ; while true ; do ((count++)) ; echo fallocate -l ${count}00KB /fake_file ; fallocate -l ${count}00KB /fake_file; sleep 1; done"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            ephemeral-storage: "1Mi"
          limits:
            ephemeral-storage: "1Mi"
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate

