apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: patch-manager
  namespace: default
  labels:
    app: patch-manager
spec:
  selector:
    matchLabels:
      app: patch-manager
  template:
    metadata:
      labels:
        app: patch-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
      containers:
      - name: patchmgr
        image: ubuntu:4.2.1
