apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: patch-manager
  namespace: default
  labels:
    app: patch-manager
    app.kubernetes.io/instance: splunk-datagens
spec:
  selector:
    matchLabels:
      app: patch-manager
  template:
    metadata:
      labels:
        app: patch-manager
        app.kubernetes.io/instance: splunk-datagens
    spec:
      serviceAccountName: cleaner
      containers:
      - name: patchmgr
        args:
        - sh
        - -c
        - 'SSD_LABEL=$(kubectl get node $NODE_NAME -o jsonpath="{.metadata.labels.disktype}")
          ; while [ -z "$SSD_LABEL" ] ; do echo {\"severity\" : \"error\", \"message\"
          : \"Patch-manager: Checking for pods that need patching\"} ; echo {\"severity\":\"info\",
          \"message\":\"Patch-manager: No pods to patch found.\"} ; sleep 300 ; done
          ; echo {\"severity\" : \"error\", \"message\" : \"Patch-manager: Cannot
          run on node with given disktype. Failing\"}'
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
 
        image: portainer/kubectl-shell:latest
#        resources:
#         requests:
#           cpu: "2"
