apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: patch-manager
  namespace: default
  labels:
    app: patch-manager
    app.kubernetes.io/instance: splunk-datagens
spec:
  selector:
    matchLabels:
      app: patch-manager
  template:
    metadata:
      labels:
        app: patch-manager
        app.kubernetes.io/instance: splunk-datagens
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
      containers:
      - name: patchmgr
        args:
        - sh
        - -c
        - while true; do sleep 20000 ; done
        image: busybox
#        resources:
#         requests:
#           cpu: "2"
