apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: higher-priority
value: 1000
globalDefault: false
description: "A class for higher-priority pods.  Used for stress-ng pods"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng-deployment
  labels:
    app:  stress-ng-deployment
    app.kubernetes.io/instance: splunk-datagens
spec:
  replicas: 5
  selector:
    matchLabels:
      app: stress-ng
  template:
    metadata:
      labels:
        app: stress-ng
        app.kubernetes.io/instance: splunk-datagens
    spec:
      priorityClassName: higher-priority
      containers:
      - name: stress-ng
        image: colinianking/stress-ng
        command:
          - sh
          - -c 
          - "while true ; do stress-ng --cpu 40 -t $(shuf -i 300-600 -n 1) ; sleep $(shuf -i 400-800 -n 1); done"
        imagePullPolicy: IfNotPresent
      dnsPolicy: ClusterFirst
      nodeSelector:
        stresstest: "true"
  strategy:
    type: RollingUpdate
