name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

#      - name: Create Dynamic Dummy File to trigger chart rebuild
#        run: |
#          DUMMY_FILE="charts/splunk-k8s-o11y-datagen/templates/force-release.yaml"
#          echo "#Triggering release at $(date)" > "$DUMMY_FILE"
#          git add "$DUMMY_FILE"
#          git commit -m "Update dummy file to trigger release" || echo "No changes to commit"
#          git push || echo "No changes to push"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
